### ISSUE TITLE
[Android] shortcut badger

### ISSUE THREAD

**Issue by abdelwehed** [nguquen/react-native-shortcut-badger#1]
Hello everyone,
I'm new in react native and i want to add a shortcut badge to my android app representing the number of notifications. While searching in the internet i found this package but i don't know how to use it.
Any help please in how can i implement this in my simple project.
Thanks in advance :)

**Comment by nguquen** [comment]
Sorry guy, i'll update README soon :)

**Comment by nguquen** [comment]
@abdelwehed : I added a README file with the instruction, check it out

**Comment by hamzarebaichkaw** [comment]
Thank you very much for updating the README.
I already installed and linked the package but i didn't get where to put this in my code:BadgeNumberAndroid.setNumber(5)

**Comment by abdelwehed** [comment]
Hello  @nguquen ,
I have the same issue, i added in the componentDidMount() function in my home file but i can't get it work. Should i run it on device to have it work ?

**Comment by nguquen** [comment]
@abdelwehed It only works on supported launchers, you must run it on device that has supported launchers. You can see list of supported launchers at [https://github.com/leolin310148/ShortcutBadger](https://github.com/leolin310148/ShortcutBadger)

**Comment by abdelwehed** [comment]
Hello,
Sorry for the late response, but i could get it worked now.
